baseurl = "https://eunhanlee.github.io/"
languageCode = "en-us"
title = "Eunhan's library"
theme = "blackburn"
author = "Eunhan Lee"
copyright = "&copy; 2021. All rights reserved."
canonifyurls = true
paginate = 10

[blackfriday]
    extensions = ["hardLineBreak"]
 
[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"


[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Eunhan's personal web site / portfolio"
  brand = "library"
  googleAnalytics = "poiqqaz"
  disqus = "eunhanlee"
  dateFormat = "02 Jan 2006"
  custom_css = ["css/button.css"]


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "All Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
    
    
#  [[menu.main]]
#    name = "HowToInstall"
#    pre = "<i class='fas fa-chalkboard fa-fw'></i>"
#    weight = 4
#    identifier = "HowToInstall"
#    url = "/topics/HowToInstall/"
#  [[menu.main]]
#    name = "Projects"
#    pre = "<i class='fas fa-file-code fa-fw'></i>"
#    weight = 5
#    identifier = "Projects"
#    url = "/topics/Projects/"
   [[menu.main]]
    name = "CodeKnowledge"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 6
    identifier = "CodeKnowledge"
    url = "/topics/CodeKnowledge/"
  [[menu.main]]
    name = "ProblemSolving"
    pre = "<i class='fas fa-puzzle-piece fa-fw'></i>"
    weight = 7
    identifier = "ProblemSolving"
    url = "/topics/ProblemSolving/"
  [[menu.main]]
    name = "CodingQuestions"
    pre = "<i class='far fa-question-circle fa-fw'></i>"
    weight = 8
    identifier = "CodingQuestions"
    url = "/topics/CodingQuestions/"
  [[menu.main]]
    name = "Java"
    pre = "<i class='fas fa-code fa-fw'></i>"
    weight = 9
    identifier = "Java"
    url = "/topics/Java/"
    
    
    
    
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    identifier = "tag"
    weight = 300
    url = "/tags/"


[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  # twitter="*"
  # gnusocial="*"
  # facebook="*"
  # weibo="*"
  # tumblr="*"
  # instagram="*"
  # flickr="*"
  # photo500px="*"
  # pinterest="*"
  # youtube="*"
  # vimeo="*"
  # vine="*"
  # slideshare="*"
  linkedin="eh4925"
  # xing="*"
  # reddit="*"
  # hackernews="*"
  github="eunhanlee"
  # gitlab="*"
  # bitbucket="*"
  # stackoverflow="*"
  # serverfault="*"
  # steam="*"
  # mobygames="*"
  # lastfm="*"
  # discogs="*"
  # keybase="*"
